name: lakes
description: Demonstrates building a layout for the "Lakes" app.

dependencies:
  http: ^0.12.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider: ^0.4.1
  image_picker: ^0.4.4

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg
